[package]
name = "{{ project_name }}_bin"
version.workspace = true
edition.workspace = true

[[bin]]
name = "{{ project-name }}"
path = "src/main.rs"

[dependencies]
{{ project_name }}_core = { path = "../{{ project_name }}_core" }
{% if persistence ~= 'None' %}{{ project_name }}_persistence = { path = "../{{ project_name }}_persistence" }
{% endif %}{% if cache ~= 'None' %}{{ project_name }}_cache = { path = "../{{ project_name }}_cache" }
{% endif %}{% if messaging ~= 'None' %}{{ project_name }}_messaging = { path = "../{{ project_name }}_messaging" }
{% endif %}{% if has_s3 %}{{ project_name }}_storage_s3 = { path = "../{{ project_name }}_storage_s3" }
{% endif %}{% if has_azure_blob %}{{ project_name }}_storage_azure = { path = "../{{ project_name }}_storage_azure" }
{% endif %}
anyhow = "1"
axum = "0.8"
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15"
figment = { version = "0.10", features = ["toml", "env"] }
opentelemetry = { version = "0.27", features = ["trace"] }
opentelemetry-otlp = { version = "0.27", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.27", features = ["rt-tokio"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
toml = "0.8"
tracing = "0.1"
tracing-opentelemetry = "0.28"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
