[package]
name = "{{ prefix_name }}_{{ suffix_name }}_core"
version.workspace = true
edition.workspace = true

[dependencies]
{% if persistence ~= 'None' %}{{ prefix_name }}_{{ suffix_name }}_persistence = { path = "../{{ prefix_name }}_{{ suffix_name }}_persistence" }
{% endif %}{% if cache ~= 'None' %}{{ prefix_name }}_{{ suffix_name }}_cache = { path = "../{{ prefix_name }}_{{ suffix_name }}_cache" }
{% endif %}{% if messaging ~= 'None' %}{{ prefix_name }}_{{ suffix_name }}_messaging = { path = "../{{ prefix_name }}_{{ suffix_name }}_messaging" }
{% endif %}
anyhow = "1"
axum = { version = "0.8", features = ["macros"] }
metrics = "0.24"
metrics-exporter-prometheus = { version = "0.16", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
{% if persistence == 'PostgreSQL' %}sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-rustls"] }
{% endif %}{% if persistence == 'MySQL' %}sqlx = { version = "0.8", features = ["mysql", "runtime-tokio-rustls"] }
{% endif %}thiserror = "2"
tokio = { version = "1", features = ["rt"] }
tower-http = { version = "0.6", features = ["trace", "cors"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }
